version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    working_directory: ~/wisdomKeep
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: npm install
      # - run: sudo apt-get update && sudo apt-get install sshpass
      - save_cache:
          key: node_modules
          paths:
            - node_modules
      - run: npm run build
      # 部署开始
      - restore_cache:
          keys:
            - node_modules
      - add_ssh_keys:
          fingerprints:
            - "f3:d2:92:55:8a:12:d2:e4:21:7a:cb:b2:bd:6e:4d:0b"
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              scp -r ./adist root@47.104.180.119:/www/wwwroot/              
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
