version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    working_directory: ~/wisdomKeep
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      # 部署开始
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "74:85:4a:1c:7f:01:88:1b:c0:93:32:d9:fd:6c:f4:fa"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              sudo scp -i  ./adist root@47.104.180.119:/www/wwwroot/              
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
