version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    working_directory: ~/wisdomKeep

    steps:
      - checkout
      - restore_cache:
          keys: node_modules
      - run: sudo npm install -g npm
      - run: npm install
      - run: sudo apt-get update && sudo apt-get install sshpass
      - save_cache:
          key: node_modules
          paths:
            - node_modules
      - run: npm run build
      # 部署开始
      - add_ssh_keys:
          fingerprints:
            - "SHA256:D8w9BcbDN7bzjhLCKnd0mNSt6McXiRkYssGvNxuE0pc"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: sudo scp -r ./adist root@121.43.162.95:/www/wwwroot/
      - run: echo '部署完毕'
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
